version: "3.3"
services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
        - ${CONFIG}:/app/config.yml
        - ${LOGS_FOLDER}:/app/logs/
    environment:
        - BOT_TOKEN=${BOT_TOKEN}
        - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
        - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
        - MYSQL_HOST=db
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=chiya
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
        - ${DATABASE_FOLDER}:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: chiya
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}