version: "3.7"
services:
  chiya:
    container_name: chiya
    build: .
    restart: unless-stopped
    volumes:
        - ./config/config.yml:/app/config.yml
        - ./config/logs:/app/logs/
    depends_on:
        - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
        - ./config/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: chiya
        MYSQL_USER: chiya
        MYSQL_PASSWORD: your_secure_password
        MYSQL_ROOT_PASSWORD: your_more_secure_password
